CLASS_DETAIL = {
    "DosGoldenEye": "Goldeneye dos attack is implemented using dos script from Kali Linux attack. The victim machine is Ubuntu 16. This is an application layer dos attack. The intent is to disrupt the service. This runs by using python script thus can be run on all Linux and Windows platforms. Victim VM gets huge requests of requests with different strings of random internet browsers. The server thinks that there may be different users try-ing to get access thus leading to depleted server resources.",
    "DosHulk": "Hulk is an application layer dos attack tool. Kali Linux and Ubuntu VM are used as attackers and victims. It is an HTTP flood tool that uses unique and obfuscated traf-fic volume. Due to its obfuscation, it is more difficult to detect as compared to other DOS attack tools due to their predictable repeated patterns. The main principle for this tool is to generate a unique pattern at every request so that it can evade any in-trusion detection and prevention systems. This attack causes a high number of pack-ets leading to a high flow count.",
    "DosLOIC": "How does the LOIC work? It works by flooding a target server with TCP, UDP, or HTTP packets with the goal of disrupting service. One attacker using the LOIC can’t generate enough junk traffic to make a serious impact on a target; serious attacks require thousands of users to coordinate a simultaneous attack on the same target. In order to make these coordinated attacks easier, users can use IRC chat channels to run a ‘Hivemind’ version of the LOIC which lets one primary user control several networked secondary computers, creating a voluntary botnet.",
    "DosSlowHttp": "This attack is like slowloris and a kind of stealthier and interactive version. It can also act as a slowloris attack. The attacker machine is kali Linux whereas the victim machine is Ubuntu16. This application layer dos attack tool uses low bandwidth and consumes server resources by concurrent connection pool. As we know that HTTP protocol relies upon completing the request before they get processed. Hence, if the connection speed is slow, the server must be busy waiting for complete requests by the client thus making them inaccessible for legitimate users.",
    "DosSlowloris": "Slowloris attack is done using slowloris.py python script from Kali Linux. Victim machine is ubuntu 16 and ubuntu 12. This attack works by sending partial HTTP re-quests to consume all connections to the webserver which are never completed. Hence, it intends to consume all the system resources thus disrupting system service. The webserver is contacted with a large number of connections and the connections stay for a long time. A specialty of this tool is that although it may take time but, in the end, it wins thus named slowloris because it consumes the sockets one by one.",
    "FTPPatator": "Brute-force attack on FTP protocol is performed using the patator tool. FTP protocol is used for file transfer between clients and servers. It requires a valid username and password. This attack is used to extract the login ID and password of the user to get access to the remote system. The victim is Ubuntu 16 having FTP service running. Username and password files that were used in SSH brute-force attacks are also used here.",
    "SSHPatator": "Patator, a Kali Linux tool is used to perform brute force attacks on SSH protocol. SSH is a protocol that is used to secure multiple services over the internet. Its most common use is to log in from a remote server. Victim VM is Ubuntu 16 having an SSH service running.",
    "SqlInjWeb": "SQL injection is one of the most popular attacks on the internet targeting vulnerable webforms that take unsanitized queries from users. The database layer of the web application is exploited that directly uses user input in the database queries. Major queries include stealing and deletion of database data using queries. The victim is a DVWA application configured on Ubuntu 16 and the attacker machine is Kali Linux. This attack is quite difficult to detect because it contains almost similar traffic to that of normal traffic. Just a small change in user input query can lead to this dan-gerous attack.",
    "XssWeb": "This attack is similar to the SQL injection attack where we inject malicious scripts into the unsanitized user inputs. Once a malicious script is injected, victims will be presented with the malicious script when they access the website. This may result in fraud, malicious script execution, and data theft. DVWA application is used to per-form this attack from Kali Linux OS. This attack is also difficult to detect as in the case of SQL injection.", 
    "heartbleed": "Heartbeat is an important part of TLS protocol. It is used to confirm that the corre-sponding device is online. It is a vulnerability of the OpenSSL library that is imple-mented in the TLS protocol. Heartbeat operates by a technique where a client sends some random payload to the server. Then, server must reply to the client with the same payload. This is called heartbeat request and response. The client also must specify the length of the random payload. Here, comes vulnerability. There is no check on the length and actual payload sent by the client. ",
    "httpWebAttack": "For HTTP brute-force attack, we have configured the DVWA app. Damn Vulnerable Web App (DVWA) is a web application that is vulnerable and used to carry on net-work attacks. In its Brute-force section, we have a webpage that is used to test the network attacks. Patator tool is used to implement this attack. The behavior of this attack is quite similar to the previously mentioned brute-force attacks. ", 
    "portscan": "It is a popular attack that is used in the reconnaissance part of the attack. Attack gathers information about systems using this attack and plans how will they intrude into the system. We can get the information of operating systems, possible vulnera-bilities, running services, and port statuses. In a PortScan attack, the attacker tries to communicate to each port that normally ranges from 0 to 65535 and then interpret from the response whether this port is being used or not thus leading to the detection of weak entry points. It uses different types of scans including syn scan, fin scan, UDP scan, etc. ", 
    "normal": "Your Traffic seems like normal nothing malicious is detected" 
    }